# -*- coding: utf-8 -*-
"""Write prototype/manifest.json from the same tables the board draws from.

Generated, never hand-kept: the ids come out of data.js and the file list comes
off disk, so the manifest cannot describe an asset that is not there or miss one
that is. Every path is a PATH — nothing in this bundle is base64.
"""
import json, pathlib, math
from PIL import Image
import numpy as np
HERE = pathlib.Path(__file__).resolve().parent.parent
ROOT = HERE.parent.parent
MK = ROOT / "assets" / "mk"
REL = "assets/mk"                       # relative to the app's own index.html
TOPICS = ROOT / "assets" / "topics"
TREL = "assets/topics"

src = (ROOT / "data.js").read_text(encoding="utf-8")
D = json.loads(src[src.index("{"):src.index("const AVATARS")].rstrip().rstrip(";").rstrip())

# THE LIST COMES OFF DISK, not out of a tuple kept by hand here. A stem is
# accepted only if it is a data.js politician id AND both exports exist, so a
# half-written pair, a stray style-comparison file, or a source with no data.js
# id (lazimi, may_golan, ohanah, troper — a client question, not a fix) can
# never reach the manifest. Adding a portrait is running frame_mk.py; nothing
# in this file has to be edited to keep up.
PORTRAITS = tuple(sorted(
    pid for pid in D["politicians"]
    if (MK / ("mk_%s_400.webp" % pid)).exists()
       and (MK / ("mk_%s_128.webp" % pid)).exists()))
# THE MAP'S TOPIC ICONS — one drawn object per topic, all eight, framed by
# tools/prep_topic.py into assets/topics/. The value is the FILE STEM, which is
# the topic id for seven of them and deliberately is not for the eighth.
#
# internal_sec IS THE POLICE HAT. Two files were rejected for that node and
# both are still on disk:
#   assets/mk/internal_sec_main.png   a PADLOCK. Seven object nodes and one
#       padlock reads as "this topic is locked", and locks are on the §3.3 /
#       §8 NEVER list for the map. Retired from here; the issue cards may
#       still reference the framed set, so the files stay.
#   assets/topics/internal_sec_main.webp   a SHIELD carrying a Star of David.
#       A national symbol where the other seven are neutral objects — a
#       receipt, a lectern, a plant, a briefcase. Left in place, unregistered.
# The hat is the neutral object for משטרה, פשיעה ונשק, so it is the one used.
TOPIC_ICONS = {
    "accountability": "accountability",
    "branches":       "branches",
    "economy":        "economy",
    "environment":    "environment",
    "gender":         "gender",
    "internal_sec":   "policehat",
    "military":       "military",
    "religion":       "religion",
}
# THE SMALLEST SIZE EACH OBJECT STILL READS AT, judged on the exports
# themselves at 4x nearest-neighbour against the node's own ground — not
# asserted, and not the same number for all eight. The map renders at 60px off
# the 64px file, so every one of these is comfortably inside its floor; this is
# here so a future screen that wants a 40px topic icon knows which three it
# cannot have.
#   economy   the receipt IS its ruled lines and its torn zigzag edge. At 40px
#             the rules mush into a red block and the tear flattens: it reads
#             as a red slip of paper, not as a receipt.
#   religion  the seal IS its scalloped rim. At 40px the scallops round off to
#             a plain disc and the two ribbon tails merge into one blob.
#   gender    the beam and the two hanger strings are 1px hairlines at 40px and
#             largely dissolve; the pans survive as two dashes. Marginal, not
#             gone — 52 is the honest floor.
# The other five are objects with one strong silhouette and hold at 40.
READS_DOWN_TO = {
    "accountability": 40, "branches": 40, "economy": 64, "environment": 40,
    "gender": 52, "internal_sec": 40, "military": 40, "religion": 64,
}

ISSUE_ART = {"s1": ("internal_sec_s1", 300, 180),
             "s2": ("internal_sec_s2", 116, 210)}

def need(name):
    p = MK / name
    assert p.exists(), "manifest names a file that is not on disk: " + name
    return "%s/%s" % (REL, name)

def need_topic(name):
    p = TOPICS / name
    assert p.exists(), "manifest names a file that is not on disk: " + name
    return "%s/%s" % (TREL, name)

def need_asset(rel):
    """An asset under assets/ that is not part of the MK set. Same guarantee:
    the manifest cannot name a file that is not there."""
    assert (ROOT / rel).exists(), "manifest names a file that is not on disk: " + rel
    return rel

man = {
    "_": ("Generated by tools/make_manifest.py. Ids are data.js's own. "
          "Sizes are the pixel size each file is written at: pick the entry that "
          "matches the size you are rendering at and never let the browser "
          "downscale a file more than 1.2x."),
    "portrait_aspect": "3:4 — 400x533 and 128x171",
    "portrait_crop_rule": {
        "face_width_pct_of_frame": 68.3,
        "crown_pct_from_top": 2.4,
        "anchor": "crown",
        "note": ("Top-anchored in the card at --mk-port-top. The bottom is the "
                 "variable edge: a long figure clips at the jacket, never at the head."),
    },
    "politicians": {},
    "topics": {},
    "issues": {},
    "props": {
        "chair": {"300": need("knesset_chair_300.webp"), "128": need("knesset_chair_128.webp"),
                  "aspect": round(300 / 350, 4)},
        "building": {"390": need("knesset_building_390.webp")},
        # the deck's card back, drawn full-bleed and bottom-anchored
        "card_back": {"file": need_asset("assets/card_background.webp")},
    },
}

for pid in PORTRAITS:
    assert pid in D["politicians"], pid
    man["politicians"][pid] = {
        "name": D["politicians"][pid]["name"],
        "party": D["politicians"][pid].get("party", ""),
        "400": need("mk_%s_400.webp" % pid),
        "128": need("mk_%s_128.webp" % pid),
    }
missing = [p for p in D["politicians"] if p not in PORTRAITS]
man["politicians_without_art"] = sorted(missing)
man["fallback"] = {
    "kind": "initials-badge",
    "rule": ("First letter of each part of the shipped name, joined with a gershayim, "
             "set on the set's own eyeline at 37.7% of the box. NEVER substitute "
             "another politician's portrait."),
}

# ASPECT AND VISUAL MASS ARE MEASURED, NOT DECLARED. The map sizes an icon by
# its LARGER dimension and derives the other from the aspect, so a hand-typed
# ratio here would silently stretch the artwork. Both numbers are read off the
# 128px export — the same file the smaller ones were cut from.
#
# node_scale IS WHY THE EIGHT NO LONGER LOOK LIKE EIGHT DIFFERENT SIZES.
# Sizing every icon so its LARGER DIMENSION is the same makes a solid round
# seal read enormous and a tall narrow receipt read small: the eye weighs
# area, not the longest edge. So each icon is scaled to a common AREA, and
# node_scale is the per-icon multiplier that does it, normalised so the eight
# average 1.0 — the map multiplies it by --node-ico-avg and nothing else.
#
# THE AREA IS THE GEOMETRIC MEAN of the ink area (opaque pixels) and the box
# area (w*h), and the middle is where it belongs. Equalising BOX area ignores
# density, so a hairline drawing and a solid block come out the same size.
# Equalising INK area over-rewards sparse line art: measured on this set it
# pushes the scales to 80.6px wide on a 76px disc — wider than the node they
# sit on — while shrinking the briefcase to 45. sqrt(ink * box) splits the
# difference and keeps every icon inside the ring.
def node_mass(stem):
    im = Image.open(TOPICS / ("%s_128.webp" % stem)).convert("RGBA")
    ink = int((np.array(im)[..., 3] > 8).sum())
    return math.sqrt(ink * im.width * im.height), im.size

_mass = {tid: node_mass(stem) for tid, stem in TOPIC_ICONS.items()}
# a scale is 1/sqrt(mass); normalise so the mean MAX DIMENSION is 1.0
_raw = {tid: 1.0 / math.sqrt(m) for tid, (m, _) in _mass.items()}
_mean = sum(_raw[t] * max(_mass[t][1]) for t in _raw) / len(_raw)

for tid, stem in sorted(TOPIC_ICONS.items()):
    assert any(t["id"] == tid for t in D["topics"]), (
        "topic icon has no matching topic id in data.js: " + tid)
    man["topics"][tid] = {k: need_topic("%s_%d.webp" % (stem, k))
                          for k in (40, 52, 64, 128, 256)}
    w, h = _mass[tid][1]
    man["topics"][tid]["aspect"] = round(w / h, 4)
    man["topics"][tid]["node_scale"] = round(_raw[tid] * max(w, h) / _mean, 4)
    man["topics"][tid]["source"] = stem
    man["topics"][tid]["reads_down_to"] = READS_DOWN_TO[tid]
# the emoji stays the fallback for a topic with no drawn object. There are none
# today; the loop is the guarantee, not a placeholder.
for t in D["topics"]:
    if t["id"] not in man["topics"]:
        man["topics"][t["id"]] = {"glyph": t["icon"]}

for iid, (stem, w, h) in ISSUE_ART.items():
    assert any(i["id"] == iid for i in D["issues"]), iid
    man["issues"][iid] = {"file": need("%s_%d.webp" % (stem, max(w, h))),
                          "w": w, "h": h}

out = HERE / "prototype" / "manifest.json"
out.write_text(json.dumps(man, ensure_ascii=False, indent=2), encoding="utf-8")
print("wrote %s — %d politicians with art, %d without, %d topic icons, %d issue graphics"
      % (out.relative_to(HERE), len(man["politicians"]),
         len(man["politicians_without_art"]),
         sum(1 for v in man["topics"].values() if "glyph" not in v),
         len(man["issues"])))
